# Generated by Django 5.2.5 on 2025-08-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbooks', '0005_remove_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
